export const BOOKS = [
  { id: 1, title: "The Sealed Nectar", author: "Safi-ur-Rahman al-Mubarakpuri", category: "Islamic" },
  { id: 2, title: "Riyad-us-Saliheen", author: "Imam Nawawi", category: "Islamic" },
  { id: 3, title: "Tafsir Ibn Kathir", author: "Ibn Kathir", category: "Islamic" },
  { id: 4, title: "Fortress of the Muslim", author: "Said bin Ali Al-Qahtani", category: "Islamic" },
  { id: 5, title: "Purification of the Heart", author: "Hamza Yusuf", category: "Islamic" },
  { id: 6, title: "Atomic Habits", author: "James Clear", category: "Self-Help" },
  { id: 7, title: "How to Win Friends and Influence People", author: "Dale Carnegie", category: "Self-Help" },
  { id: 8, title: "The 7 Habits of Highly Effective People", author: "Stephen R. Covey", category: "Self-Help" },
  { id: 9, title: "Can't Hurt Me", author: "David Goggins", category: "Self-Help" },
  { id: 10, title: "Mindset: The New Psychology of Success", author: "Carol S. Dweck", category: "Self-Help" },
  { id: 11, title: "Rich Dad Poor Dad", author: "Robert Kiyosaki", category: "Finance" },
  { id: 12, title: "Think and Grow Rich", author: "Napoleon Hill", category: "Finance" },
  { id: 13, title: "The Psychology of Money", author: "Morgan Housel", category: "Finance" },
  { id: 14, title: "$100 Startup", author: "Chris Guillebeau", category: "Business" },
  { id: 15, title: "Zero to One", author: "Peter Thiel", category: "Business" },
  { id: 16, title: "The Lean Startup", author: "Eric Ries", category: "Business" },
  { id: 17, title: "DotCom Secrets", author: "Russell Brunson", category: "Business" },
  { id: 18, title: "A Beginner's Guide to Forex Trading", author: "Matthew Driver", category: "Trading" },
  { id: 19, title: "Trading in the Zone", author: "Mark Douglas", category: "Trading" },
  { id: 20, title: "E-Commerce Business Model 2023", author: "Chloe Thomas", category: "Business" },
  { id: 21, title: "The 4-Hour Body", author: "Tim Ferriss", category: "Health" },
  { id: 22, title: "Eat That Frog!", author: "Brian Tracy", category: "Productivity" },
  { id: 23, title: "Make Your Bed", author: "William H. McRaven", category: "Self-Help" },
  { id: 24, title: "Deep Work", author: "Cal Newport", category: "Productivity" },
  { id: 25, title: "Tools of Titans", author: "Tim Ferriss", category: "Self-Help" },
];

export const LANGUAGES = [
  { code: "en", name: "English" },
  { code: "ur", name: "Urdu" },
  { code: "ar", name: "Arabic" },
  { code: "hi", name: "Hindi" },
  { code: "es", name: "Spanish" },
  { code: "fr", name: "French" },
  { code: "de", name: "German" },
];
